name: Test our Secret Value

on: [workflow_dispatch]

env:
  ## Sets environment variable

  API_KEY: ${{secrets.API_KEY}}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: logs out Api key
        run: echo API_KEY
